### ISSUE TITLE
Bundle / deploy does not give error when using ui url as api

### ISSUE THREAD

**Issue by odama626** [staticdeploy/staticdeploy#66]
This is a fantastic tool that I had spent literally days looking for before finding this one!

Something that would improve the cli experience:

I accidentally used the ui url as the api url when first trying it and the cli returned success leading to some confusion. Providing an error message for this issue would make it easier for new users.

**Comment by pscanf** [comment]
Hey @odama626 , very glad you like it! Feel free to ask if you need any support.

Regarding the incorrect feedback from the CLI, I quickly reproduced it following the quickstart and definitely it's not the intended behaviour. I'll mark this as a bug and look into it. Thanks for the report!
