### ISSUE TITLE
Request body larger than maxBodyLength

### ISSUE THREAD

**Issue by odama626** [staticdeploy/staticdeploy#68]
When trying to bundle an app I ran into an error 
```
error: Error: Request body larger than maxBodyLength limit
```

**Comment by pscanf** [comment]
Hey @odama626 , currently there's a ~80MB limit on the size of the uploaded bundle. If you do a `tar -zcvf bundle.tar.gz your-app-build-folder/` is the produced `bundle.tar.gz` file larger than ~80MB? (The limit is not configurable right now, but it's trivial to increase it / make it configurable)

**Comment by odama626** [comment]
It looks like one of them is 25mb and the other is 37.. I did just update the cli though, I wonder if it could be caused by a version mismatch between the client and server?  The 25mb bundle has been deployed successfully before

**Comment by pscanf** [comment]
Ah, bad news then. Looking around, I think it might be due to this axios/axios#2781 breaking change (unfortunately not listed as such), which I pulled in updating dependencies. Using the `v0.15.2` CLI should fix it. I'll push a fix for that tonight. Thanks for the catch!

**Comment by pscanf** [comment]
Fixed in `v0.15.4`.
