### ISSUE TITLE
Common styling

### ISSUE THREAD

**Issue by djKooks** [staticdeploy/staticdeploy#70]
Hello~
This is just a question about minor issue.

While reading a code, seems common styling rule is not adopt in the projects.
> Because seems it recommends to use semi-colon at end of line, but several codes don't have it

Do you have plan for updates?

**Comment by pscanf** [comment]
Hello @djKooks, code styling is enforced on the whole codebase using [prettier](https://prettier.io/), which is configured (by default) to automatically insert semicolons at the end of lines. Prettier is even runs as a CI check, see for example the **Run linters** step of [this CI run](https://app.circleci.com/pipelines/github/staticdeploy/staticdeploy/31/workflows/ad3a4170-5c46-4a71-82ef-fd027c678f00/jobs/848). It's possible however that I missed to include some file in the check. If you have an example could you link it here? Thanks!

**Comment by djKooks** [comment]
@pscanf hello.
Sorry, seems it is my mistake. Currently I couldn't find styling issue. Thanks for following~
