### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by tbjers** [staticdeploy/staticdeploy#84]
Not a single commit to this repository for at least three years. Repository is not deprecated. The lights are on, but is anyone home?

**Comment by pscanf** [comment]
The project is still working and being used, but it's almost feature complete for my needs, so there's not gonna be many changes. It could use a dependency update, though.

**Comment by tbjers** [comment]
> The project is still working and being used, but it's almost feature complete for my needs, so there's not gonna be many changes. It could use a dependency update, though.

@pscanf Awesome, thank you for getting back to me so quickly! I will get a PR in with dependency updates.
